def save_character_to_file(stats,character_data,character_details,equipment,filename="character.txt"):
    try:
        with open(filename, 'w', encoding="utf-8") as file:
            file.write(f"""
            
Imie: {character_data.get("name")}      Wiek: {character_details[0]}
  
Rasa: {character_data.get("race")}      Wzrost: {character_details[1]}

Klasa: {character_data.get("class")}    Szybkość: {character_details[2]}   

        STATYSYKI                               EKWIPUNEK
        
Siła:           {stats[0]}              {equipment[0]}  
Zręczność:      {stats[1]}              {equipment[1]}
Kondycja:       {stats[2]}              .........................
Inteligencja:   {stats[3]}              .........................              
Mądrość:        {stats[4]}              .........................  
Charyzma:       {stats[5]}              .........................  

        UMIEJĘTNOŚCI
                                            
............................
............................          
............................
............................
............................
............................
............................
............................
............................
............................
            """)
    except Exception as e:
        print(e)
if __name__ == "__main__":
    print("d")